import Head from "next/head";

import HeroSection from "components/common/Hero/Hero";
import { Categories, Product, ProductCategory } from "types/types";
import getProducts from "utils/getProduct.util";
import ProductCarousel from "components/ProductCarousel";

type HomepageProps = {
  sortedItems: SortedItems[];
};

export default function HomePage({ sortedItems }: HomepageProps) {
  return (
    <div>
      <Head>
        <title>Echo Store </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />

      {sortedItems.map(({ category, products }) => (
        <ProductCarousel
          title={category}
          key={category}
          products={products}
          category={category}
        />
      ))}
    </div>
  );
}
export async function getServerSideProps() {
  const products = await getProducts();
  const sortedItems: SortedItems[] = Categories.map((category) => ({
    category,
    products: products.filter((x: any) => x.category === category),
  }));

  const props: HomepageProps = { sortedItems };

  return {
    props,
  };
}

type SortedItems = {
  category: ProductCategory;
  products: Product[];
};
