name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      # install dependencies
      - run: yarn install
      # run ESLint & Prettier
      - run: yarn lint
      - run: yarn  prettier
      # verify that there are no type and build errors
      - run: yarn build
      # run tests with Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn start
